import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-8">
        <nav className="flex gap-2 border p-2">
          <Link href="/">Home</Link>
          <Link href="/product/1">Product 1</Link>
          <Link href="/product/2">Product 2</Link>
          <Link href="/product/3">Product 3</Link>
        </nav>

        <Suspense fallback="Loading">
          <div className="p-4">{children}</div>
        </Suspense>
      </body>
    </html>
  );
}
